### PR TITLE
Fix cannot open skill without Internet

### PR DESCRIPTION
**Pull request by lcgao**
[Open developed apps without an internet connection](https://roboteam.atlassian.net/browse/ROBO-9934)

### CODE REVIEW

**Comment by brad-oosterveld** [comment]
I can not open the sample app that is currently on master when my Temi is not connected to the internet. Is that the intended behavior? If so what do I need to change to allow it run when not connected to the internet? Thanks!

**Comment by ramisaban1** [comment]
Hello Brad,

Thank you for reaching out to temi's support. This is a bug we are addressing within the next couple of versions. When this becomes available, you will be notified under the Development updates section of the temi Software Update email.

Once this does become available, you will need to declare a meta-data that allows the app to be opened without the internet.

### Example:

```
      <meta-data
            android:name="@string/metadata_open_without_internet"
            android:value="TRUE" />
```

Sorry I couldn't be of more help.

Best,
Rami

**Comment by brad-oosterveld** [comment]
Hi Rami,

Thanks for following up! Do I need to do anything to subscribe to the Temi
Software Update email?

Best,
Brad

**Comment by ramisaban1** [comment]
The email address used when purchasing _temi_ will be receiving these update emails. If you are currently using a different email address and would like to receive those emails elsewhere, please reach out to our live chat or email us at support@robotemi.com with your updated email address and they should be able to update your information so that you receive the upcoming software update emails.

**Pull request merged**
